package com.example.weather.utils

const val API_KEY_PROPERTIES = "X-Yandex-API-Key"
const val LATITUDE = "Lat"
const val LONGITUDE = "Lon"
const val MESSAGE_DISCONNECT = "Отсутствует подключение к сети"
const val  MESSAGE_CONNECT = "Подключение к сети восстановлено"
const val MESSAGE_MAKE_CONNECT = "Подключитесь к сети и повторите запрос"
const val EXIT_APP = "Выйти из приложения"
const val MESSAGE_ERROR = "Ошибка доступа к данным погоды"
const val MESSAGE_APP_CLOSE = "Приложение будет закрыто"
const val MESSAGE_LAUNCH_APP_TITLE = "Открыть приложение Weather"
const val MESSAGE_LAUNCH_APP_TEXT = "Нажмите, чтобы открыть приложение Weather"
const val CHANNEL_ID = "ChannelIDForWeatherNotification"
const val CHANNEL_NAME = "ChannelForWeather"
const val END_POINT = "v2/informers"
const val BASE_URL = "https://api.weather.yandex.ru/"
const val CONDITION_ICON_URL = "https://yastatic.net/weather/i/icons/funky/dark/%s.svg"
